items_in_cart = "//*[@data-action-field='bp']"
notification_in_cart = "//*[@class='cart-primary__title']"
total_in_cart = "//*[@class='cart-summary-totals__value--thick']"
plus_button = "//*[@class='tooltip-trigger quantity-buttons-cart__select js-cart-quantity js-quantity']"
first_item_in_cart = "(//*[@data-action-field='bp'])[1]"
second_item_in_cart = "(//*[@data-action-field='bp'])[2]"
delete_item_from_cart_button = "(//*[@value='Usuń produkt'])[1]"
empty_cart_notification = "//*[@class='cart-empty__title']"
go_to_main_page_button= "//*[@class='button cart-empty__button']"