accept_cookies_button = "//*[@id='onetrust-accept-btn-handler']"
close_promo_window_button = "//*[@id='close-button-1454703513202']"
search_string = "//*[@id='q']"
find_button = "//*[contains(text(),'więcej wyników wyszukiwania')]"
search_results = "//*[@class='product-tile__name']"
header_search_text = "//*[@class='category-header__search-text']"
account_icon = "//*[@href='https://www.hebe.pl/account']"
create_account_button = "//*[@title='Załóż konto']"
no_hebe_card_button = "//*[@title='nie mam karty My Hebe']"
logout_button = "//*[@title='Wyloguj się']"
first_product = "(//*[@class='product-tile   js-product-tile  '])[1]"
add_to_favorites_button = "(//*[@title='Dodaj do listy życzeń'])[1]"
favorites_quantity_icon = "//*[@class='header-button__badge js-wishlist-quantity']"
favorites_heart_button = "(//*[@class='wishlist-icon__svg wishlist-icon__svg--full'])[1]"
add_to_cart_button = "//*[@title='DODAJ DO KOSZYKA']"
cart_icon = "//*[@class='header-button__badge']"
go_to_cart_button = "//*[@class='button product-set-dialog__button']"
continue_shopping_button = "//*[@class='button button--outline js-close-modal']"
pop_up_window = "//*[@class='everyday-promo__arrow js-everyday-promo-minimize-trigger']"
